#!/usr/bin/with-contenv sh

source /etc/colors.sh

PREFFIX="[cont-finish.d] $(s6-basename ${0}):"

#s6-svc -d /var/run/s6/services/rclone-mount
#s6-svc -wD /var/run/s6/services/rclone-mount

echo -e "${PREFFIX} ${Yellow}waiting for shutdown of all services${Color_Off}"
#wait for all services to be down
s6-svwait -D /var/run/s6/services/*

#awk '/efsgoogle:/ && /\'$ENVIRON["MOUNT_PATH"]'/ {print; exit 1}' /proc/mounts

#check if rclone gracefully unmounted
if grep -Eq ''$REMOTE_PATH'.*'$MOUNT_PATH'|'$MOUNT_PATH'.*'$REMOTE_PATH'' /proc/mounts; then
    echo -e "${PREFFIX} ${Red}force unmounting with fusermount $UNMOUNT_COMMANDS at: $(date +%Y.%m.%d-%T)${Color_Off}"
    fusermount $UNMOUNT_COMMANDS $MOUNT_PATH
    wait ${!}
    exit 1
else
    #cleanup of mount namespace
    umount $MOUNT_PATH
    echo -e "${PREFFIX} ${Green}successful unmounted${Color_Off}"
    exit 0
fi
