#!/usr/bin/with-contenv sh

source /etc/colors.sh

PREFFIX="[cont-init.d] $(s6-basename ${0}):"

#ENV
OS=""

#Functions
DetectOS(){
  if [ -e /etc/alpine-release ]; then
    OS="alpine"
  elif [ -e /etc/os-release ]; then
    if /bin/grep -q "NAME=\"Ubuntu\"" /etc/os-release ; then 
      OS="ubuntu"
    fi
  fi
}

AutoUpgrade(){
  if [ "${OS}" == "alpine" ]; then
      /sbin/apk --no-cache upgrade
      /bin/rm -rf /var/cache/apk/*
  elif [ "${OS}" == "ubuntu" ]; then
      export DEBIAN_FRONTEND=noninteractive
      /usr/bin/apt-get update
      /usr/bin/apt-get -y --no-install-recommends dist-upgrade
      /usr/bin/apt-get -y autoclean
      /usr/bin/apt-get -y clean 
      /usr/bin/apt-get -y autoremove
      /bin/rm -rf /var/lib/apt/lists/*
  fi
}

# Create folders
mkdir -p \
  $MOUNT_PATH \
  $CONFIG_PATH

printf "$CONFIG_PATH/$CONFIG_FILE" > /var/run/s6/container_environment/CONFIG

echo -e "${PREFFIX} ${Blue}installing system updates${Color_Off}"
DetectOS
AutoUpgrade
