name: Docker

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      # run: docker build --no-cache --tag qnimbus/rclone:testing docker-rclone/
      run: make -C docker-rclone/ build
